### ISSUE TITLE
Create Architecture Overview

### ISSUE THREAD

**Issue by iemwill** [bumi/fourohtwo#1]
Maybe we can start with some kind of Overview, with what we will need and how every section talks to the other ones. As an example here is the Architecture of Metamask:
![grafik](https://user-images.githubusercontent.com/33894930/47208172-6699b900-d38d-11e8-88d0-b30d4d3e26af.png)

**Comment by bumi** [comment]
yep, good idea!
what do we have? 

* browser + extension that connects to the lnd gRPC interface
* lnd node 
* server / paywall

**Comment by iemwill** [comment]
what do you mean by paywall, and do we have to choose in first place a specific browser, or can we do it in general and it will work for all browsers?

**Comment by bumi** [comment]
The basic idea would be that if the browser responds with a `402 Payment Required` HTTP status the browser plugin allows the user to perform the payment and reloads the page. 
See the wiki for notes about the [idea and a sequence diagram](https://github.com/bumi/fourohtwo/wiki#how-does-it-work)

I don't know too much about the different options to build browser plugins. But all are basically HTML/JS to at least for Firefox and Chrome most of the code should be reusable.

**Comment by iemwill** [comment]
what what should we start with. For fun i created a branch to make a first plugin test. It worked^^

**Comment by bumi** [comment]
whoot, awesome, will check it out. that sounds good! 
did you see the links to plugin documentation and examples in the wiki? 

in this issue we should draw a diagram of the planned architecture - guess that was your idea here, right?

**Comment by iemwill** [comment]
Yeeees you kind of did that in the wiki, right? And another yees, i started with the links in the wiki and created a first „border plugin“ which is documented in one of the links.

**Comment by iemwill** [comment]
To edit the existing diagram follow this workflow:
draw.io -> open existing diagram -> ./docs/...xml
