### ISSUE TITLE
create a "background-script" listening to 402-payment requests

### ISSUE THREAD

**Issue by iemwill** [bumi/fourohtwo#5]
To get the Plugin listen to lightning payment invoices we should have it listen to the 402 request. Further steps need to be Added as:
- what exactly will be in the Header
- do we have to listen to other requests

TBC...

**Comment by bumi** [comment]
The plugin probably would "intercept" the request/response. 
There are some docs here: 

* [Mozilla docs - webRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest) 
* [Mozilla docs - intercept HTTP requests](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Intercept_HTTP_requests)

**Comment by iemwill** [comment]
The second link is used in the branch, web-request.

**Comment by iemwill** [comment]
Vielleicht sollten wir auch auf url's der Form: '''lightning:lnbc1549500130p1pdl2aa7pp5k3jm....'''
achten, also mit beginnend "lightning:", viele websiten haben das schon so integriert...(siehe blockstream)

**Comment by bumi** [comment]
yeah, super idee!! 
oder auch wenn einfach eine lightning invoice in der seite gefunden wird.
